{
    "name": "Stripe",
    "version": '19.0.0',
    "category": "other/",
    "license": "AGPL-3",
    "summary": "Stripe-Odoo Integration using REST API's AND Scheduler Action",
    "author": "ManojParmar",
    "maintainers": ["Manoj Parmar"],
    "website": "www.abc.com",
    "depends": [],
    "data": [
        # "security/ir.model.access.csv",
        # "views/.xml",
        # "report/.xml",
        # "data/.xml",
    ],
    "installable": True,
    'auto_install': False,
    "application": True,
}
