{
    'name': 'Real Estate',
    'version': '1.0',
    'summary': 'Real Estate Practise Module version 19',
    'sequence': -1,
    'description': 'Real Estate Practise Module version 19',
    'category': 'Extra Tools',
    'author': 'Manoj PArmar',
    'maintainer': 'Manoj PArmar',
    'company': 'Manoj PArmar',
    'website': 'https://www.google.com',
    'depends': ['mail', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        # 'report/paperformat.xml',
        # 'report/.xml',
        'views/estate_property_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        
        'views/estate_menus.xml',   
        # 'report/template.xml',
    ],
    'demo': [],
    # 'images': ['static/description/'],
    # 'css': ['static/src/'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    # 'post_init_hook': ''
}
