{
    "name": "Sale Order API",
    "version": '19.0.0',
    "category": "other/",
    "license": "AGPL-3",
    "summary": "PayPal-Odoo Integration using REST API's AND Scheduler Action",
    "author": "Manoj Parmar",
    "maintainers": ["Manoj Parmar"],
    "website": "www.abc.com",
    "depends": ['sale'],
    "data": [
        # "security/ir.model.access.csv",
        # "views/.xml",
        # "report/.xml",
        # "data/multiple_cron.xml",
    ],
    "installable": True,
    'auto_install': False,
    "application": True,
}
